resources:
- name: simple-java-src
  type: git
  source:
    uri: https://github.com/hprotzek/simple-java.git
    branch: master
- name: deploy
  type: cf
  source:
    api: "https://api.europe-west1.cf.gcp.springernature.io"
    username: ((cf-credentials.username))
    password: ((cf-credentials.password))
    organization: engineering-enablement
    space: dev

jobs:
- name: test
  plan:
  - get: simple-java-src
    trigger: true

  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: openjdk, tag: 8-jdk}
      inputs:
      - name: simple-java-src
      run:
        dir: simple-java-src
        path: ./gradlew
        args: ["clean", "test"]

- name: build-deploy
  plan:
  - get: simple-java-src
    trigger: true
    passed: [test]

  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: openjdk, tag: 8-jdk}

      inputs:
      - name: simple-java-src
      outputs:
      - name: simple-java-bin
      run:
        dir: simple-java-src
        path: ./gradlew
        args: ["-PbuildDir=../simple-java-bin", "build"]

  - task: debug
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}

      inputs:
      - name: simple-java-bin

      run:
        dir: simple-java-bin
        path: ls
        args: ["libs"]

  - put: deploy
    params:
      manifest: simple-java-src/manifest.yml
      path: ../simple-java-bin/libs/simple-java-0.0.1-SNAPSHOT.jar
