resources:
  - name: simple-java
    type: git
    source:
      uri: https://github.com/hprotzek/simple-java.git
      branch: master
  - name: stage
    type: cf
    source:
      api: (( api ))
      username: (( username ))
      password: (( password ))
      organization: (( organization ))
      space: (( space ))

jobs:
- name: test
  plan:
    - get: simple-java
      trigger: true
    - task: build
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8-jdk
      inputs:
        - name: simple-java
      run:
        dir: simple-java
        path: gradlew
        args: clean test

- name: build-deploy
  plan:
    - get: simple-java
      passed: [test]
    - task: build
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8-jdk
      inputs:
        - name: simple-java
      run:
        dir: simple-java
        path: gradlew
        args: clean build
      outputs:
        - name: deploy-artefact
          path: build
    - put: deploy
      params:
        manifest: simple-java/manifest.yml